### ISSUE TITLE
populate drugs structure property table

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/coderdata#142]
need to add drug structure/fingerprints.

**Comment by sgosline** [comment]
also need to add mordred descriptors

**Comment by jjacobson95** [comment]
@sgosline What are your thoughts on changing the schema for Drug Descriptor to have three columns, improve_drug_id, fingerprint, and mordred?

Also what should these files be called?  "{dataset}_drug_descriptor.tsv"? or "{dataset}_structures.tsv"?


Current Schema:
```
  Drug:
    description: List of chemicals/drugs used in the data package. Each identifer corresponds to a distinct structure.
    slots:
      - improve_drug_id
    attributes:
      chem_name:
        description: Name of drug
      canSMILES:
        description: Canonical SMILE string
      isoSMILES:
        description: Isomeric SMILE string
      InChIKey:
        description: InChIKey
      formula:
        description: Chemical formula
      weight:
        description: Molecular weight
        range: float
      pubchem_id:
        description: PubChem Identifier for this drug, can be many.
        range: int
  Drug Descriptor:
    description: Computational summary of drug chemical properties
    slots:
      - improve_drug_id
    attributes:
      structural_descriptor:
        description: string name describing structural descriptor
      descriptor_value:
        range: any
        description: value representing descriptor value
```
